spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    username: ak
    url: jdbc:h2:mem:testdb
#    url: jdbc:postgresql://localhost:5432/employee_management
    password: akpass
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
server:
  port: 9000
  error:
    path: /error
    whitelabel:
      enabled: false